### ISSUE TITLE
Modificar la información de los grupos

### ISSUE THREAD

**Issue by booleanchile** [ngChile/escalando-aplicaciones-con-angular#37]
Se necesita modificar los grupos en la página de Login y es necesario incluir:

- Grupo 1
- Grupo 2
- Aprobador

**Comment by tacevedo** [comment]
Hoy existen 5 grupos (A,B,D,E,F), segun las instrucciones se deben agregar 3 grupos.
Debo mantener los grupos existentes?

**Comment by samuelmedin** [comment]
Se deben mantener los grupos existentes. solo dejar 3. eliminar 2 grupos, se adjunta print esperado.
![image](https://user-images.githubusercontent.com/48572227/54399935-646b2a80-469f-11e9-8d2d-46f564734425.png)
