### ISSUE TITLE
Eliminar las advertencias 'required:true' y de estado del formulario

### ISSUE THREAD

**Issue by booleanchile** [ngChile/escalando-aplicaciones-con-angular#38]
Quitar texto "impreso" en el HTML en la pantalla de login en el input de Grupos (cuando se deja el campo sin llenar) y los datos del formulario.

**Comment by booleanchile** [comment]
![Captura de pantalla 2019-03-11 a las 12 00 03 a m](https://user-images.githubusercontent.com/46203382/54098020-7db76280-4391-11e9-89a2-d2ddd2bcee33.png)
![Captura de pantalla 2019-03-10 a las 11 59 52 p m](https://user-images.githubusercontent.com/46203382/54098021-7db76280-4391-11e9-9dc1-563b737bf5ea.png)

**Comment by ebustosmerino** [comment]
Es solo para el campo Grupo o también se requiere para Email y Password

**Comment by samuelmedin** [comment]
eliminar para todos los campos el estado 'required:true'. como se indic a en la imagen

![image](https://user-images.githubusercontent.com/48572227/54400182-61246e80-46a0-11e9-8c9f-1b007cc3133e.png)
